name: Docker build and push to GCR repo

on:
  push:
    branches:
      - main

jobs:
  build_and_push_base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [6,8,10,12,14,16]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GCR
        uses: docker/login-action@v1 
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      -
        name: Build and push base images
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          context: ./base/${{ matrix.versions }}
          push: true
          tags: signalnoise/base:${{ matrix.versions }}
      -
        name: Base image digest
        run: echo ${{ steps.docker_build_base.outputs.digest }}
  build_and_push_enhanced:
    runs-on: ubuntu-latest
    needs: build_and_push_base # because they require the base images to be in GCR already
    strategy:
      matrix:
        images: [e2e]
        versions: [10,12,14,16]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GCR
        uses: docker/login-action@v1 
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      -
        name: Build and push enhanced images
        id: docker_build_enhanced
        uses: docker/build-push-action@v2
        with:
          context: /${{ matrix.images }}/${{ matrix.versions }}
          push: true
          tags: signalnoise/${{ matrix.images }}:${{ matrix.versions }}
      -
        name: Enhanced image digest
        run: echo ${{ steps.docker_build_enhanced.outputs.digest }}