name: Docker build and push to GCR repo

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        builds: [base,e2e]
        nodeversions: [10,12,14,16]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GCR
        uses: docker/login-action@v1 
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: /${{ matrix.builds }}/${{ matrix.nodeversions }}
          push: true
          tags: signalnoise/${{ matrix.builds }}:${{ matrix.nodeversions }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}